---
- name: Make Fresh RSS Etc folder
  ansible.builtin.file:
    path: "{{ freshrss_etc }}"
    state: directory
    mode: '0755'
    owner: '{{ freshrss_service_user }}'
    group: '{{ freshrss_service_user }}'

- name: Find the php socket
  ansible.builtin.find:
    paths: "{{ php_home }}"
    patterns: "php*.*.sock"
    file_type: any
  register: find_results

- name: Set fact to found file
  ansible.builtin.set_fact:
    phpfpm_socket: "{{ (find_results.files | first).path }}"

- name: Set MariaDB user password
  ansible.builtin.slurp:
    src: "/etc/mysql/user_{{ mariadb_dbuser }}"
  register: mariadb_dbuser_pwd_raw
  when: not (mariadb_dbuser_pwd | default(""))

- name: Set fact to found file
  ansible.builtin.set_fact:
    mariadb_dbuser_pwd: "{{ mariadb_dbuser_pwd_raw.content }}"

- name: Chown freshrss P
  ansible.builtin.file:
    path: "{{ freshrss_dir }}/p"
    state: directory
    recurse: true
    owner: '{{ nginx_user }}'
    group: '{{ nginx_user }}'

- name: Change the directory permissions for Fresh RSS dir
  ansible.builtin.file:
    path: "{{ freshrss_dir }}"
    state: directory
    recurse: true
    mode: '0755'

- name: Chown freshrss data
  ansible.builtin.file:
    path: "{{ freshrss_dir }}/data"
    state: directory
    recurse: true
    owner: '{{ nginx_user }}'
    group: '{{ nginx_user }}'

- name: Template Nginx config file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_default_config_path }}"
    force: true
    mode: '0770'
  notify: "Restart Nginx"

- name: Set Fresh RSS Admin Password since it was provided
  ansible.builtin.set_fact:
    freshrss_admin_password: "{{ freshrss_admin_pass }}"
  when: freshrss_admin_pass
  no_log: true

- name: Create Fresh RSS Admin Password since it was not provided
  ansible.builtin.set_fact:
    freshrss_admin_password: "{{ lookup('community.general.random_string', length=24, special=false) }}"
  when: not freshrss_admin_pass
  no_log: true

- name: Drop copy of Fresh RSS Admin Password on local box
  ansible.builtin.copy:
    content: "{{ freshrss_admin_password }}"
    dest: "{{ freshrss_local_user_password_path }}"
    force: true
    owner: "root"
    group: "root"
    mode: "0700"
  when: freshrss_local_user_password_path
  no_log: true

- name: Make Encrypted Password for Fresh RSS
  ansible.builtin.set_fact:
    freshrss_admin_enc_pw: "{{ freshrss_admin_password | password_hash('bcrypt', rounds=9) }}"
  no_log: true

- name: Print the value of the variable freshrss_admin_enc_pw
  ansible.builtin.debug:
    msg: "freshrss_admin_enc_pw: {{ freshrss_admin_enc_pw }} "


- name: Check if Fresh RSS has been initialized
  ansible.builtin.stat:
    path: "{{ fresrss_config_init_path }}"
  register: fresrss_config_init

- name: Initialize Fresh RSS
  block:

    - name: Make command execution for Install
      set_fact:
        fressrss_install_command_var: >-
            ./cli/do-install.php
            --default_user {{ freshrss_admin_user }}
            [
            --auth_type form
            --environment production
            --base_url {{ freshrss_base_url }}
            --language en
            --title FreshRSS
            --allow_anonymous
            --api_enabled
            --db-type mysql
            --db-host localhost:3306
            --db-user {{ mariadb_dbuser }}
            --db-password {{ mariadb_dbuser_pwd }}
            --db-base {{ mariadb_dbname }}
            --db-prefix freshrss
            ]
      no_log: true

    - name: Run the Install Command for FreshRSS
      ansible.builtin.shell:
        cmd: "{{ fressrss_install_command_var }}"
        chdir: "{{ freshrss_dir }}"
      no_log: true

    - name: Make command execution for Admin User
      set_fact:
        fressrss_makeuser_command_var: >-
            ./cli/create-user.php
            --user {{ freshrss_admin_user }}
            [
            --password '{{ freshrss_admin_password }}'
            ]
      no_log: true

    - name: Run the Make User Command for FreshRSS
      ansible.builtin.shell:
        cmd: "{{ fressrss_makeuser_command_var }}"
        chdir: "{{ freshrss_dir }}"
      no_log: true

    - name: Make new salt for actual config file (since most of CLI doesn't work)
      ansible.builtin.set_fact:
        freshrss_newsalt: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=40') }}"

    - name: Template out new config file
      ansible.builtin.template:
        src: config.php.j2
        dest: "{{ freshrss_dir }}/data/config.php"
        force: true
        mode: '0770'
      no_log: true

    - name: Template out new user file
      ansible.builtin.template:
        src: user.config.php.j2
        dest: "{{ freshrss_admin_user_folder }}/config.php"
        force: true
        mode: '0770'
      no_log: true

  when: ((not fresrss_config_init.stat.exists) and (freshrss_initialize))

- name: Touch a file to demonstrate Fresh RSS has been initialized
  ansible.builtin.file:
    path: "{{ fresrss_config_init_path }}"
    state: touch
    mode: '0700'
  when: ((not fresrss_config_init.stat.exists) and (freshrss_initialize))

- name: Chown freshrss P
  ansible.builtin.file:
    path: "{{ freshrss_dir }}/p"
    state: directory
    recurse: true
    owner: '{{ nginx_user }}'
    group: '{{ nginx_user }}'

- name: Change the directory permissions for Fresh RSS dir
  ansible.builtin.file:
    path: "{{ freshrss_dir }}"
    state: directory
    recurse: true
    mode: '0755'

- name: Chown freshrss data
  ansible.builtin.file:
    path: "{{ freshrss_dir }}/data"
    state: directory
    recurse: true
    owner: '{{ nginx_user }}'
    group: '{{ nginx_user }}'