---
- name: Template out freshrss Service
  ansible.builtin.template:
    src: freshrss.service.j2
    dest: "/etc/systemd/system/freshrss.service"
    force: true
    mode: '0644'  # Ansible-Lint hates when this isn't set

- name: Add overwrite_certs.sh
  ansible.builtin.template:
    src: overwrite_certs.sh.j2
    dest: "{{ freshrss_dir }}/overwrite_certs.sh"
    force: true
    mode: '0700'  # Ansible-Lint hates when this isn't set
    owner: "{{ freshrss_service_user }}"
    group: "{{ freshrss_service_user }}"

- name: Copy initial cert to appropriate directory
  ansible.builtin.copy:
    src: "{{ freshrss_inital_cert_location }}/{{ freshrss_external_domain }}.crt"
    dest: "{{ freshrss_certificate_path }}"
    remote_src: true
    force: true
    owner: "{{ freshrss_service_user }}"
    group: "{{ freshrss_service_user }}"
    mode: "0700"

- name: Copy initial key to appropriate directory
  ansible.builtin.copy:
    src: "{{ freshrss_inital_cert_location }}/{{ freshrss_external_domain }}.key"
    dest: "{{ freshrss_key_path }}"
    remote_src: true
    force: true
    owner: "{{ freshrss_service_user }}"
    group: "{{ freshrss_service_user }}"
    mode: "0700"

- name: Make override directory
  ansible.builtin.file:
    path: "{{ freshrss_cert_renewer_path }}"
    state: directory
    mode: '0755'

- name: Deploy freshrss override
  ansible.builtin.template:
    src: cert-renewer.freshrss.override.j2
    dest: "{{ cert_renewer_path }}/override.conf"
    force: true
    mode: '0770'  # Ansible-Lint hates when this isn't set

- name: Do post configuration activities for freshrss
  become_user: "{{ freshrss_service_user }}"
  ansible.builtin.command:
    cmd: "{{ freshrss_post_config_command }}"
    chdir: "{{ freshrss_dir }}"
  changed_when: false

- name: Ensure cert-renewer@bitwarden.timer is started
  ansible.builtin.service:
    name: "{{ freshrss_cert_timer }}"
    state: started
    enabled: true

- name: Ensure freshrss is restarted
  ansible.builtin.service:
    name: "{{ freshrss_name }}"
    state: restarted
    enabled: true
